spring:
  mongodb:
      datasource:
        url : jdbc:mongo://localhost:27017/movieDB
        username: root
        password: 12345
        driverClassName : com.mongodb.jdbc.MongoDriver
  application:
    name: movie


server:
  port: 8090